<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>nimbob2b-api</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NimboB2B.Application\NimboB2B.Application.csproj" />
    <ProjectReference Include="..\NimboB2B.Infrastructure\NimboB2B.Infrastructure.csproj" />
    <ProjectReference Include="..\NimboB2B.Domain\NimboB2B.Domain.csproj" />
    <ProjectReference Include="..\NimboB2B.Migrations\NimboB2B.Migrations.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.7.3" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.1.2" />
  </ItemGroup>
</Project>
