import { prismaClient } from '../database';
import { ForbiddenError } from '../errors';

export class DeveloperToolsService {
  private assertDevelopment() { if (!['development', 'test'].includes(process.env.NODE_ENV ?? '')) throw new ForbiddenError('Developer tools are unavailable outside development mode.'); }
  async health() { this.assertDevelopment(); const [hubs, models, riders, deployments, categories] = await Promise.all([prismaClient.hub.count({where:{active:true}}),prismaClient.vehicleModel.count({where:{active:true}}),prismaClient.customer.count(),prismaClient.deployment.count({where:{rentalStatus:'ACTIVE'}}),prismaClient.issueCategory.count({where:{active:true}})]); return {environment:process.env.NODE_ENV,checks:{database:true,prisma:true,hubs,vehicleModels:models,riders,activeDeployments:deployments,issueCategories:categories}}; }
  async data() { this.assertDevelopment(); const riders=await prismaClient.customer.findMany({where:{registeredMobile:{in:['9000000001','9876543210','9123456780']}},include:{deployments:{where:{rentalStatus:'ACTIVE'},include:{hub:true,vehicleModel:true}}}}); return riders.map(r=>({riderName:r.name,mobile:r.registeredMobile,deployments:r.deployments.map(d=>({mvTrackNumber:d.mvTrackNumber,registrationNumber:d.vehicleNumber,hub:d.hub.name,model:d.vehicleModel.displayName,vehicleType:(d.vehicleModel as any).vehicleType??null,status:d.rentalStatus}))})); }
  async validate() { this.assertDevelopment(); const data=await this.data(); const duplicateName=data.filter(r=>r.riderName==='Rahul Das').length===2; const allActive=data.every(r=>r.deployments.length===1&&r.deployments[0].status==='ACTIVE'); return {passed:duplicateName&&allActive,checks:{searchByMobile:data.some(r=>r.mobile==='9876543210'),searchByName:data.filter(r=>r.riderName==='Rahul Das').length===2,duplicateNameResolution:duplicateName,activeDeploymentResolution:allActive,vehicleLookup:allActive,hubLookup:allActive,vehicleTypeLookup:data.every(r=>Boolean(r.deployments[0].vehicleType)),registrationNumberLookup:Boolean(data.find(r=>r.deployments[0].model==='M7')?.deployments[0].registrationNumber),multipleIssueSupport:'PENDING_CONVERSATION_EXTENSION',photoUploadStorage:'PENDING_CONVERSATION_EXTENSION',ticketCreation:'EXISTING_SERVICE_AVAILABLE',ticketRetrieval:'EXISTING_SERVICE_AVAILABLE',ticketTimeline:'EXISTING_SERVICE_AVAILABLE',ticketListRefresh:'EXISTING_UI_AVAILABLE',reviewScreenGeneration:'PENDING_CONVERSATION_EXTENSION'}}; }
}
