import * as XLSX from "xlsx";
import PDFDocument from "pdfkit";

export interface ExportFile {
  fileName: string;
  contentType: string;
  content: Buffer;
}

export interface ReportExportKpiItem {
  label: string;
  value: string | number;
}

export interface ReportExportInput {
  reportTitle: string;
  generatedBy: string;
  generatedAt: string;
  filters: Record<string, string | undefined>;
  kpiSummary?: ReportExportKpiItem[];
  rows: Record<string, unknown>[];
}

/** Shared real-file export engine for every report type (generalized from the Service Loss
 * Analytics export, which pioneered real xlsx/pdfkit output in this codebase). Replaces the
 * previous CSV-labeled-as-Excel/PDF text export in report.service.ts. */
export class ReportExportService {
  buildCsv({ rows }: ReportExportInput): ExportFile {
    const content = this.toCsv(rows);
    return {
      fileName: this.fileName("csv"),
      contentType: "text/csv",
      content: Buffer.from(content, "utf-8"),
    };
  }

  buildExcel(input: ReportExportInput): ExportFile {
    const workbook = XLSX.utils.book_new();

    const summaryRows: Array<Record<string, string | number>> = [
      { Field: "Report", Value: input.reportTitle },
      { Field: "Generated By", Value: input.generatedBy },
      { Field: "Generated At", Value: input.generatedAt },
      ...Object.entries(input.filters)
        .filter(([, value]) => value !== undefined && value !== "")
        .map(([key, value]) => ({ Field: `Filter: ${key}`, Value: String(value) })),
    ];
    if (input.kpiSummary) {
      for (const kpi of input.kpiSummary) {
        summaryRows.push({ Field: kpi.label, Value: kpi.value });
      }
    }
    XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(summaryRows), "Summary");

    XLSX.utils.book_append_sheet(workbook, XLSX.utils.json_to_sheet(input.rows), "Detail");

    const buffer = XLSX.write(workbook, { type: "buffer", bookType: "xlsx" }) as Buffer;
    return {
      fileName: this.fileName("xlsx"),
      contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      content: buffer,
    };
  }

  async buildPdf(input: ReportExportInput): Promise<ExportFile> {
    const doc = new PDFDocument({ margin: 40, size: "A4" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    const done = new Promise<Buffer>((resolve, reject) => {
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);
    });

    doc.fontSize(16).text(input.reportTitle, { align: "left" });
    doc.fontSize(9).fillColor("#555");
    doc.text(`Generated By: ${input.generatedBy}`);
    doc.text(`Generated At: ${new Date(input.generatedAt).toLocaleString()}`);
    doc.fillColor("black").moveDown();

    const appliedFilters = Object.entries(input.filters).filter(([, value]) => value !== undefined && value !== "");
    if (appliedFilters.length > 0) {
      doc.fontSize(11).text("Applied Filters", { underline: true });
      doc.fontSize(9);
      for (const [key, value] of appliedFilters) {
        doc.text(`${key}: ${value}`);
      }
      doc.moveDown();
    }

    if (input.kpiSummary && input.kpiSummary.length > 0) {
      doc.fontSize(11).text("KPI Summary", { underline: true });
      doc.fontSize(9);
      for (const kpi of input.kpiSummary) {
        doc.text(`${kpi.label}: ${kpi.value}`);
      }
      doc.moveDown();
    }

    doc.fontSize(11).text(`Detailed Records (${input.rows.length})`, { underline: true });
    doc.fontSize(8);
    const columns = input.rows.length > 0 ? Object.keys(input.rows[0]) : [];
    for (const row of input.rows.slice(0, 200)) {
      doc.text(columns.map((column) => `${column}: ${String(row[column] ?? "-")}`).join(" · "));
    }
    if (input.rows.length > 200) {
      doc.text(`… and ${input.rows.length - 200} more (see Excel export for the full list).`);
    }

    doc.end();
    const content = await done;
    return {
      fileName: this.fileName("pdf"),
      contentType: "application/pdf",
      content,
    };
  }

  private toCsv(rows: Record<string, unknown>[]): string {
    if (rows.length === 0) return "";
    const headers = Object.keys(rows[0]);
    const lines = [headers.join(",")];
    for (const row of rows) {
      lines.push(
        headers
          .map((header) => {
            const raw = row[header];
            if (Array.isArray(raw)) {
              return `"${raw.join(" | ").replace(/"/g, '""')}"`;
            }
            return `"${String(raw ?? "").replace(/"/g, '""')}"`;
          })
          .join(",")
      );
    }
    return lines.join("\n");
  }

  private fileName(extension: string): string {
    return `report-${new Date().toISOString().slice(0, 10)}.${extension}`;
  }
}
