import type { NextFunction, Request, Response } from "express";
import type { ApiResponse } from "../dto/master.dto";
import { PartsCatalogService } from "../services/parts-catalog.service";
import { PartsImportService } from "../services/parts-import.service";
import { PartInventoryTransactionService } from "../services/part-inventory-transaction.service";
import { PartsInventoryUploadService } from "../services/parts-inventory-upload.service";
import { validateConsumptionSummaryQuery, validateCreatePart, validateCreatePartAdjustment, validateCreatePartCategory, validateCreatePartSubcategory, validatePartListQuery, validateTransactionListQuery, validateUpdatePartCategory, validateUploadHistoryListQuery } from "../validators/parts.validator";
import { UnauthorizedError } from "../errors";

export class PartsController {
  constructor(
    private readonly service = new PartsCatalogService(),
    private readonly importService = new PartsImportService(),
    private readonly transactionService = new PartInventoryTransactionService(),
    private readonly uploadHistoryService = new PartsInventoryUploadService()
  ) {}
  private requireUserId(req: Request): string { if (!req.authUser) throw new UnauthorizedError("Authentication is required."); return req.authUser.userId; }
  getTemplates = async (_req: Request, res: Response, next: NextFunction) => { try { const data = await this.importService.getTemplates(); const response: ApiResponse<typeof data> = { success: true, data }; res.status(200).json(response); } catch (error) { next(error); } };
  previewCatalogImport = async (req: Request, res: Response, next: NextFunction) => { try { const workbookBase64 = typeof req.body?.workbookBase64 === "string" ? req.body.workbookBase64 : ""; if (!workbookBase64) throw new Error("workbookBase64 is required."); const data = await this.importService.previewCatalog(workbookBase64); const response: ApiResponse<typeof data> = { success: true, data }; res.status(200).json(response); } catch (error) { next(error); } };
  confirmCatalogImport = async (req: Request, res: Response, next: NextFunction) => { try { const sessionId = typeof req.body?.sessionId === "string" ? req.body.sessionId : ""; if (!sessionId) throw new Error("sessionId is required."); const data = await this.importService.confirmCatalog(sessionId); const response: ApiResponse<typeof data> = { success: true, data }; res.status(201).json(response); } catch (error) { next(error); } };
  previewInventoryImport = async (req: Request, res: Response, next: NextFunction) => { try { const workbookBase64 = typeof req.body?.workbookBase64 === "string" ? req.body.workbookBase64 : ""; if (!workbookBase64) throw new Error("workbookBase64 is required."); const fileName = typeof req.body?.fileName === "string" && req.body.fileName.trim() ? req.body.fileName.trim() : "inventory-import.xlsx"; const data = await this.importService.previewInventory(workbookBase64, fileName); const response: ApiResponse<typeof data> = { success: true, data }; res.status(200).json(response); } catch (error) { next(error); } };
  confirmInventoryImport = async (req: Request, res: Response, next: NextFunction) => { try { const sessionId = typeof req.body?.sessionId === "string" ? req.body.sessionId : ""; if (!sessionId) throw new Error("sessionId is required."); const invoiceNumber = typeof req.body?.invoiceNumber === "string" ? req.body.invoiceNumber : ""; const purchaseOrderId = typeof req.body?.purchaseOrderId === "string" && req.body.purchaseOrderId.trim() ? req.body.purchaseOrderId.trim() : undefined; const data = await this.importService.confirmInventory(sessionId, this.requireUserId(req), invoiceNumber, purchaseOrderId); const response: ApiResponse<typeof data> = { success: true, data }; res.status(201).json(response); } catch (error) { next(error); } };
  listUploadHistory = async (req: Request, res: Response, next: NextFunction) => { try { const data = await this.uploadHistoryService.list(validateUploadHistoryListQuery(req.query)); const response: ApiResponse<typeof data> = { success: true, data }; res.status(200).json(response); } catch (error) { next(error); } };
  downloadUpload = async (req: Request, res: Response, next: NextFunction) => { try { const { fileName, content } = await this.uploadHistoryService.getDownload(req.params.id); res.setHeader("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"); res.setHeader("Content-Disposition", `attachment; filename="${fileName}"`); res.status(200).send(content); } catch (error) { next(error); } };
  listCategories = async (_req: Request, res: Response, next: NextFunction) => { try { const data = await this.service.listCategories(); const response: ApiResponse<typeof data> = { success: true, data }; res.status(200).json(response); } catch (error) { next(error); } };
  createCategory = async (req: Request, res: Response, next: NextFunction) => { try { const data = await this.service.createCategory(validateCreatePartCategory(req.body)); const response: ApiResponse<typeof data> = { success: true, data }; res.status(201).json(response); } catch (error) { next(error); } };
  createSubcategory = async (req: Request, res: Response, next: NextFunction) => { try { const data = await this.service.createSubcategory(validateCreatePartSubcategory(req.body)); const response: ApiResponse<typeof data> = { success: true, data }; res.status(201).json(response); } catch (error) { next(error); } };
  listParts = async (req: Request, res: Response, next: NextFunction) => { try { const data = await this.service.listParts(validatePartListQuery(req.query)); const response: ApiResponse<typeof data> = { success: true, data }; res.status(200).json(response); } catch (error) { next(error); } };
  createPart = async (req: Request, res: Response, next: NextFunction) => { try { const data = await this.service.createPart(validateCreatePart(req.body)); const response: ApiResponse<typeof data> = { success: true, data }; res.status(201).json(response); } catch (error) { next(error); } };
  updatePartCategory = async (req: Request, res: Response, next: NextFunction) => { try { const data = await this.service.updatePartCategory(req.params.id, validateUpdatePartCategory(req.body)); const response: ApiResponse<typeof data> = { success: true, data }; res.status(200).json(response); } catch (error) { next(error); } };
  createAdjustment = async (req: Request, res: Response, next: NextFunction) => { try { const data = await this.transactionService.createAdjustment(req.params.id, this.requireUserId(req), validateCreatePartAdjustment(req.body)); const response: ApiResponse<typeof data> = { success: true, data }; res.status(201).json(response); } catch (error) { next(error); } };
  listTransactions = async (req: Request, res: Response, next: NextFunction) => { try { const data = await this.transactionService.listTransactions(validateTransactionListQuery(req.query)); const response: ApiResponse<typeof data> = { success: true, data }; res.status(200).json(response); } catch (error) { next(error); } };
  getConsumptionSummary = async (req: Request, res: Response, next: NextFunction) => { try { const data = await this.transactionService.getConsumptionSummary(validateConsumptionSummaryQuery(req.query)); const response: ApiResponse<typeof data> = { success: true, data }; res.status(200).json(response); } catch (error) { next(error); } };
}
