export enum LogEvent {
  // Session lifecycle events
  SESSION_CREATED = "SESSION_CREATED",
  SESSION_RESUMED = "SESSION_RESUMED",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  SESSION_RESET = "SESSION_RESET",
  SESSION_DELETED = "SESSION_DELETED",

  // Customer/deployment events
  CUSTOMER_LOOKUP_SUCCESS = "CUSTOMER_LOOKUP_SUCCESS",
  CUSTOMER_LOOKUP_FAILED = "CUSTOMER_LOOKUP_FAILED",
  DEPLOYMENT_LOOKUP_SUCCESS = "DEPLOYMENT_LOOKUP_SUCCESS",
  DEPLOYMENT_LOOKUP_FAILED = "DEPLOYMENT_LOOKUP_FAILED",
  CUSTOMER_LINKED = "CUSTOMER_LINKED",

  // Ticket events
  TICKET_CREATION_STARTED = "TICKET_CREATION_STARTED",
  TICKET_CREATION_SUCCESS = "TICKET_CREATION_SUCCESS",
  TICKET_CREATION_FAILED = "TICKET_CREATION_FAILED",
  TICKET_CREATED = "TICKET_CREATED",
  TICKET_LINKED = "TICKET_LINKED",
  ISSUE_ADDED = "ISSUE_ADDED",

  // Conversation events
  CONVERSATION_STARTED = "CONVERSATION_STARTED",
  CONVERSATION_COMPLETED = "CONVERSATION_COMPLETED",
  STATE_CHANGED = "STATE_CHANGED",
  CONTEXT_UPDATED = "CONTEXT_UPDATED",
  COMMAND_RECEIVED = "COMMAND_RECEIVED",
  PHOTO_PLACEHOLDER_RECEIVED = "PHOTO_PLACEHOLDER_RECEIVED",
  PHOTO_SKIPPED = "PHOTO_SKIPPED",
  PHOTO_COLLECTION_COMPLETED = "PHOTO_COLLECTION_COMPLETED",
  MOBILE_RECEIVED = "MOBILE_RECEIVED",
  MOBILE_NORMALIZED = "MOBILE_NORMALIZED",

  // Notification events
  NOTIFICATION_SENT = "NOTIFICATION_SENT",
  NOTIFICATION_FAILED = "NOTIFICATION_FAILED",

  // Status events
  STATUS_CHANGED = "STATUS_CHANGED",

  // Error/validation events
  VALIDATION_FAILED = "VALIDATION_FAILED",
  OPERATION_FAILED = "OPERATION_FAILED",
}

export type LogEventType = `${LogEvent}`;

export function isValidLogEvent(value: unknown): value is LogEvent {
  if (typeof value !== "string") {
    return false;
  }
  return Object.values(LogEvent).includes(value as LogEvent);
}
